apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanger-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: tahalc/myapp
          ports:
            - containerPort: 9099

---
apiVersion: v1
kind: Service
metadata:
  name: taskmanager-service
spec:
  type: NodePort
  selector:
    app: taskmanager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9099
      nodePort: 30008
